export const booksMenu: string[] = [
  "Arts & Photography",
  "Biographies & Memoirs",
  "Books on CD",
  "Business & Money",
  "Calendars",
  "Children's Books",
  "Christian Books & Bibles",
  "Comics & Graphic Novels",
  "Computers & Technology",
  "Cookbooks, Food & Wine",
  "Crafts, Hobbies & Home",
  "Deals in Books",
  "Education & Teaching",
  "Engineering & Transportation",
  "Health, Fitness & Dieting",
  "History",
  "Humor & Entertainment",
  "Law",
  "Lesbian, Gay, Bisexual & Transgender Books",
  "Libros en español",
  "Literature & Fiction",
  "Medical Books",
  "Mystery, Thriller & Suspense",
  "Parenting & Relationships",
  "Politics & Social Sciences",
  "Reference",
  "Religion & Spirituality",
  "Romance",
  "Science & Math",
  "Science Fiction & Fantasy",
  "Self-Help",
  "Sports & Outdoors",
  "Teens",
  "Test Preparation",
  "Textbooks",
  "Travel",
];
