interface Book {
    id: number,
    title: string,
    author: string,
    review: number,
    material: string,
    price: number,
    cover: string
}

export const books: Book[] = [
    {
        id: 1,
        title: "It Ends with Us: A Novel (1)",
        author: "Colleen Hoover",
        review: 218702,
        material: "Paperback",
        price: 9.99,
        cover: "https://images-na.ssl-images-amazon.com/images/I/81s0B6NYXML._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 2,
        title: "Spare",
        author: "Prince Harry The Duke of Sussex",
        review: 25733,
        material: "Hardcover",
        price: 22.40,
        cover: "https://images-na.ssl-images-amazon.com/images/I/91Szm8FpdfL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 3,
        title: "It Starts with Us: A Novel (It Ends with Us)",
        author: "Colleen Hoover",
        review: 77866,
        material: "Paperback",
        price: 10.49,
        cover: "https://images-na.ssl-images-amazon.com/images/I/71PNGYHykrL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 4,
        title: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
        author: "James Clear",
        review: 93735,
        material: "Hardcover",
        price: 14.11,
        cover: "https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 5,
        title: "Saved: A War Reporter's Mission to Make It Home",
        author: "Benjamin Hall",
        review: 0,
        material: "Hardcover",
        price: 29.99,
        cover: "https://images-na.ssl-images-amazon.com/images/I/713F+ivM9NL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 6,
        title: "Little Blue Truck's Valentine: A Valentine's Day",
        author: "Alice Schertle",
        review: 8897,
        material: "Hardcover",
        price: 8.99,
        cover: "https://images-na.ssl-images-amazon.com/images/I/817-Vrzp+tL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 7,
        title: "The Creative Act: A Way of Being",
        author: "Rick Rubin",
        review: 105,
        material: "Hardcover",
        price: 19.59,
        cover: "https://images-na.ssl-images-amazon.com/images/I/A1YhM3oRFbL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 8,
        title: "Lessons in Chemistry: A Novel",
        author: "Bonnie Garmus",
        review: 88413,
        material: "Hardcover",
        price: 18.26,
        cover: "https://images-na.ssl-images-amazon.com/images/I/71yNgTMEcpL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 9,
        title: "Verity",
        author: "Colleen Hoover",
        review: 209968,
        material: "Paperback",
        price: 10.98,
        cover: "https://images-na.ssl-images-amazon.com/images/I/41ZLnc34EiL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 10,
        title: "Never Give an Inch: Fighting for the America I Love",
        author: "Mike Pompeo",
        review: 26,
        material: "Hardcover",
        price: 20.99,
        cover: "https://images-na.ssl-images-amazon.com/images/I/71XS8x7ykIL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 11,
        title: "The 48 Laws of Power",
        author: "Rovert Greene",
        review: 57616,
        material: "Paperback",
        price: 13.59,
        cover: "https://images-na.ssl-images-amazon.com/images/I/71aG+xDKSYL._AC_UL600_SR600,400_.jpg",
    },
    {
        id: 12,

        title: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
        author: "Bessel van der Kolk M.D",
        review: 60138,
        material: "Paperback",
        price: 11.40,
        cover: "https://images-na.ssl-images-amazon.com/images/I/61NdJMwAThS._AC_UL600_SR600,400_.jpg",
    },
]